name: hope is not victory
favicon: null
layout_spectrum: 0.92585
typography_spectrum: 0.23347
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#737373'
    - '#c9c9c9'
    - '#3d3d3d'
    - '#060606'
  brandStrength: 0.45329459058120847
  lightness: 0.08996931230649352
  saturation: 0.07183027430437505
  rhythmicContrast: 0.4489638756494969
purpose: []
